### ISSUE TITLE
Doubts about CIUS-ES-FACE

### ISSUE THREAD

**Issue by dgrmunch** [phax/ph-cii#2]
Hi!

Please, can you let me know if the ph-cii library includes support for CIUS-ES-FACE?

https://administracionelectronica.gob.es/ctt/resources/Soluciones/334/Descargas/CIUS-ES-FACE-1-0-0.pdf?idIniciativa=334&idElemento=15972

In case the answer is negative, how could it be included?

This question is similar to https://github.com/phax/ph-ubl/issues/23

Thanks!

**Comment by phax** [comment]
A CIUS is defined to be a total subset of the EN, and as such, every CIUS must be readable with the generic superset parser.
Therefore, without testing it, I'm pretty sure, the CIUS can be read with the D16B parser from this project.

**Comment by dgrmunch** [comment]
Do you mean that including the requirements of the CIUS would only affect to the values of the attributes we are actually binding into the XML nodes, rather than to the structure of the XML itself?

**Comment by phax** [comment]
Yes exactly!

**Comment by phax** [comment]
A CIUS can change stuff from optional to mandatory, limit code list code ranges, limit numeric value ranges etc but never add new elements or the like

**Comment by dgrmunch** [comment]
Wonderful! :)
