### ISSUE TITLE
Unable to build un.unece.*

### ISSUE THREAD

**Issue by dgrmunch** [phax/ph-cii#3]
Hey Philip!

I am testing this project and I have not been able to get the classes under the un.unece package:
```
import un.unece.uncefact.data.standard.crossindustryinvoice._100.CrossIndustryInvoiceType;
```
I have tried with "mvn clean install". Am I missing something?

Thanks!

**Comment by phax** [comment]
Well, the generated classes reside in `target/generated-sources/d16b` - did you look there?
BR, Philip

**Comment by phax** [comment]
I assume that answered the question
