### ISSUE TITLE
Which schema is the correct one for an XRechnung using CII?

### ISSUE THREAD

**Issue by Loeckmann** [phax/ph-cii#5]
We are currently working on the e-invoice. We would like to create an XRechnung. We intend to use the CII language. Which XSD schema is the correct one? d16b or d22b?

**Comment by phax** [comment]
The correct Schema for XRechnung is D16B as specified by the EN16931.

If you would ask me for my personal recommendation, I suggest you use UBL 2.1 instead. CII is very limited to Germany and France - UBL is used around the globe :)

**Comment by Loeckmann** [comment]
Thank you for your recommendation, but if I really want to use CII, which schema would be the correct one? d16b or d22b?

**Comment by Loeckmann** [comment]
Thank you so much for your incredibly quick response. I really appreciate it.
